finish assignment 14-15
webprogramminghack/assignment-class14-15 pull request #2
Opened 2024-09-22 09:18 UTC by novelyr

2024-09-22 10:36 UTC, webprogramminghack requested changes

2024-09-22 10:36 UTC, webprogramminghack commented on src/1.generic-constraints/index.ts
> +  S extends ObjectType,
Daripada extends ke ObjectType lebih baik extends ke `Record<string, any>` atau `Record<any, any>`, berhubung kita tidak menggunakan symbol, lebih baik menggunakan `Record<string, any>`.

2024-09-22 10:36 UTC, webprogramminghack commented on src/1.generic-constraints/index.ts
> +>(source: S, mapping: M): { [K in keyof M]: S[M[K]] } {
Return type nya salah.

Pertama, kita perlu menghilangkan readonly seperti ini:
-readonly [K in keyof M]: S[M[K]]

Kedua, kalau propertinya tidak ada di mapping, dengan cara seperti itu maka original propertynya akan terhapus.

Ketiga, kalau return typenya cukup complex, lebih baik dibuat menjadi sebuah type alias seperti ini:
```
 type Mapping<S, M extends Record<string, keyof S>> = {
  -readonly [K in keyof M]: S[M[K]];
} & Omit<S, M[keyof M]>;
```

Dengan cara ini return type nya jadi rapi karena kita cukup panggil `: Mapping<S, M>` saja.

Nah, kode intersect berikut gunanya supaya original propertynya tidak hilang saat kita tidak memasukkannya di mapping.
```
& Omit<S, M[keyof M]>
```

Contohnya:
```
const mapping2 = {
  id: 'userId',
  name: 'userName',
} as const;
```

Disini userAge nya tidak kita mapping, tapi ga usah khawatir karena kita intersect dengan `& Omit<S, M[keyof M]>`

2024-09-22 10:45 UTC, webprogramminghack requested changes

2024-09-22 10:45 UTC, webprogramminghack commented on src/2.infer/index.ts
> +type ItemColor<Item extends string> =
Idenya bagus, tapi tetap sedikit redundant, lebih baik optional type dibuat 1x saja tapi bisa dipakai berulang seperti ini:

```
type ExtractItem<S extends string> =
  S extends `${string}-${infer Color}-${infer Code}`
    ? { color: Color; code: Code }
    : never;

function getAvailableItems<
  C extends ExtractItem<(typeof items)[number]>['color'],
  S extends ExtractItem<(typeof items)[number]>['code']
>(color: C, code: S): (typeof items)[number][] {
  return items.filter((item) => item.includes(`${color}-${code}`));
}
```

Ga ada masalah tp untuk kodenya, constraints nya sudah berfungsi. Jadi tidak dirubah pun ga masalah. Ini hanya sedikit saran saja.

2024-09-22 10:57 UTC, webprogramminghack requested changes

2024-09-22 10:57 UTC, webprogramminghack commented on src/3.flatten/index.ts
> +type Transformer<T extends { [P in any]: any }> = {
`{ [P in any]: any }` ini selalu bisa dirubah ke `Record<any, any>` seperti yang diajarkan di materi Record di kelas.

Nah berhubung kita tidak menggunakan symbol (cuma string dan number) jadinya kita menggunakan `Record<string, any>`.

Kenapa kita tidak tulis `number | string`? Seperti yang diajarkan di kelas, ketika kita menulis string maka tipe data dari keynya sudah termasuk number juga (string | number).

Kenapa kita tidak menggunakan any? Karena any akan menghasilkan tipe data `string | number | symbol`, sedangkan kita tidak butuh symbol.

Untuk kedepannya gunakan `Record<string, any>`

2024-09-22 10:57 UTC, webprogramminghack commented on src/3.flatten/index.ts
> +  [K in keyof T]: T[K] extends infer R ? R : never;
Ini bukan solusi. Coba cek hasil tipe datanya dengan hover TransformedResult, hasilnya adalah union. Kita butuh hasil intersect.

2024-09-28 19:13 UTC, webprogramminghack requested changes

2024-09-28 19:13 UTC, webprogramminghack commented on src/1.generic-constraints/index.ts
> +  const result = {};
Kenapa kita intersect dengan `& Omit<S, M[keyof M]>;`? Tujuannya tidak lain adalah untuk mempertahankan tipe data yang tidak ada di mapping supaya tidak hilang, makanya kita intersect.

Kita ingin mempertahankan properti yang tidak ada di mapping, bukan dihilangkan.

Kode berikut akan hanya membuat properti berdasarkan value dari key yang ada di mapping:
```
const result = {};
  for (let x in mapping) {
    result[x] = source[mapping[x]];
  }
```

Apa yang terjadi kalau mappingnya seperti ini?
```
const mapping2 = {
  id: 'userId',
  name: 'userName',
} as const;
```
Di mapping tersebut tidak ada key yang memiliki value `userAge` yang menyebabkan userAge akan menghilang.

Saya kasih sedikit tips. Hal pertama yang harus dilakukan di dalam function adalah copy original object nya terlebih dahulu seperti ini:

```
const result = { ...source } as any;
```

Sisanya coba pikirkan ya.

2024-10-03 15:02 UTC, novelyr commented on src/1.generic-constraints/index.ts
> +  const result = {};
Oke pak saya coba lagi

2024-10-03 15:17 UTC, novelyr commented on src/1.generic-constraints/index.ts
> +  const result = {};
![IMG_20241003_221639.jpg](https://github.com/user-attachments/assets/bd9c51be-e71b-4c03-994e-95a20864a48c)

Ini saya cek userAge masih masuk pak?

2025-01-09 07:48 UTC, webprogramminghack requested changes
Fix the code according to the comments provided

2025-01-09 07:48 UTC, webprogramminghack commented on src/1.generic-constraints/index.ts
> +>(source: S, mapping: M): Mapping<S, M> {
Hasil sudah benar, hanya saja saya mendapatkan error berikut, pada kode `Mapping<S, M>`
![image](https://github.com/user-attachments/assets/b2511e07-29b0-43e2-93a7-0935f5b97c71)

Hal ini dikarenakan di dalam function tidak ada `return` silahkan ditambahkan terlebih dahulu

2025-01-13 06:51 UTC, webprogramminghack approved these changes
Assignment completed, good job

2025-01-13 06:51 UTC, closed without merging